<?php

$lang = array (
    'eng'=>array (
        'menu'=>array('home','about','portfolio','contact'),
        'title'=>'HELLO MY NAME IS ALAE, I’M 22 YEARS',
        'title2'=>'OLD AND I’M A FULLSTACK DEVELOPER',
        'btn1' => 'GET CV',
        'btn2' => 'HIRE ME',
        'aboutmetitle'=> 'WHO AM I?',
        'aboutmepara' => 'I\'M A FULL STACK WEB DEVELOPER PASSIONATE ABOUT PRODUCING HIGH QUALITY RESPONSIVE WEBSITES AND EXCEPTIONAL USER EXPERIENCE.YOU CAN CHECK MY GITHUB TO SEE MY PROJECTS, AND IF YOU WANT TO KNOW MORE ABOUT ME YOU CAN VISITE ABOUT SECTION.',
        'btn3'=>'SEE MORE ABOUT ALAE',
        'cmptitle'=>array('Front-end','Back-end','design','other technologies'),
        'comppara'=>array(array('- HTML5',
        '- SCSS/CSS3',
        '- JAVASCRIPT',
        '- TYPESCRIPT',
        '- JQUERY',
        '- AJAX',
        '- BOOTSTRAP',
        '- ANGULAR'),array('Conception:',
        'UML -',
        'MERISE -',
        'MS PROJECT -',
        'PROGRAMING LANGUAGES/',
        'TECHNOLOGIES:',
        'PHP 5,7 -',
        'SQL -'), 'Thus, not only I have coded their back-end and front-end code, but often I also had to care about other things needed in a successful web application: good planning of UI and thinking how it affects the UX; consistency in design and typography; tools i use: Wireframesketcher, Adobe XD, inVision Studio; Adobe Illustrator.',array('GIT(GITHUB/GITLAB) -',
        'GULP/GRANT -',
        'OTHER LIBRARIES:',
        'SAL JS/LAXXX JS/AOS JS -',
        'OTHER PROGRAMING LANGUAGES:',
        'C -',
        'PYTHON3 -')),
        'myrecentw'=>'MY RECENT WORK',
        'seemore'=>'see more',
        'whaticando'=>'what i can do?',
        'whaticandoli1'=>'Create responsive websites that work on a wide range of devices',
        'whaticandoli2'=>'Assist with production of clean and functional design',
        'whaticandoli3'=>'Bridge communication gap between designers and developers',
        'whaticandoli4'=>'I’m a full-stack developer which means I can bring your project from concept to completion.',
        'contactme'=>'contact-me',
        'modal'=>array('technologies used','close','github link')
    ),
    'fr'=>array(
        'menu'=>array('Accueil','Sur-moi','portfolio','contact'),
        'title'=>'BONJOUR JE SUIS ALAE, J\'AI 22 ANS',
        'title2'=>'ET JE SUIS UN DÉVELOPPEUR FULLSTACK',
        'btn1' => 'OBTENIR LE CV',
        'btn2' => 'ENBAUCHER MOI',
        'aboutmetitle'=> 'QUI SUIS JE?',
        'aboutmepara' => 'JE SUIS UN DÉVELOPPEUR WEB FULL STACK PASSIONNÉ DE PRODUIRE DES SITES WEB RÉACTIFS DE HAUTE QUALITÉ ET UNE EXPÉRIENCE EXCEPTIONNELLE D\'UTILISATEUR. VOUS POUVEZ CHERCHER MON GITHUB POUR VOIR MES PROJETS.',
        'btn3'=>'SAVOIR PLUS SUR ALAE',
        'cmptitle'=>array('Front-end','Back-end','Design','Autres technologies'),
        'comppara'=>array(array('- HTML5',
        '- SCSS/CSS3',
        '- JAVASCRIPT',
        '- TYPESCRIPT',
        '- JQUERY',
        '- AJAX',
        '- BOOTSTRAP',
        '- ANGULAR'),array('Conception:',
        'UML -',
        'MERISE -',
        'MS PROJECT -',
        'LANGUAGES DE PROGRAMMATION/',
        'TECHNOLOGIES:',
        'PHP 5,7 -',
        'SQL -'), 'Ainsi, non seulement j\'ai codé leurs codes back-end et front-end, mais souvent, je devais aussi me préoccuper d\'autres éléments nécessaires à la réussite d\'une application Web: une bonne planification de l\'interface utilisateur et une analyse de son affecte sur l\'UX; cohérence dans la conception et la typographie; les outils que j\'utilise: Wireframesketcher, Adobe XD, inVision Studio; Adobe Illustrator.',array('GIT(GITHUB/GITLAB) -',
        'GULP/GRANT -',
        'OTHER LIBRARIES:',
        'SAL JS/LAXXX JS/AOS JS -',
        'AUTRES LANGUAGES DE PROGRAMMATION:',
        'C -',
        'PYTHON3 -')),
        'myrecentw'=>'MON TRAVAIL RECENT',
        'seemore'=>'VOIR PLUS',
        'whaticando'=>'Qu\'est-ce que je peux faire?',
        'whaticandoli1'=>'Créez des sites Web réactifs fonctionnant sur une large gamme d\'appareils',
        'whaticandoli2'=>'Aider à la production d\'un design épuré et fonctionnel',
        'whaticandoli3'=>'combler l\'écart de communication entre les concepteurs et les développeurs',
        'whaticandoli4'=>'Je suis un développeur full-stack, ce qui signifie que je peux mener votre projet de la conception à la réalisation.',
        'contactme'=>'Contactez moi',
        'modal'=>array('technologies utilisées','Fermer','lien github')
    )
);
